export interface JukugoWord {
  word: string;
  reading: string;
  meaning: string;
}

export const jukugoList: JukugoWord[] = [
  { word: "毎日", reading: "まいにち", meaning: "setiap hari" },
  { word: "来年", reading: "らいねん", meaning: "tahun depan" },
  { word: "今年", reading: "ことし", meaning: "tahun ini" },
  { word: "今日", reading: "きょう", meaning: "hari ini" },
  { word: "明日", reading: "あした", meaning: "besok" },
  { word: "時計", reading: "とけい", meaning: "jam" },
  { word: "時間", reading: "じかん", meaning: "waktu" },
  { word: "会社", reading: "かいしゃ", meaning: "perusahaan" },
  { word: "社会", reading: "しゃかい", meaning: "masyarakat" },
  { word: "学校", reading: "がっこう", meaning: "sekolah" },
  { word: "学生", reading: "がくせい", meaning: "siswa" },
  { word: "大学", reading: "だいがく", meaning: "universitas" },
  { word: "有名", reading: "ゆうめい", meaning: "terkenal" },
  { word: "名前", reading: "なまえ", meaning: "nama" },
  { word: "午前", reading: "ごぜん", meaning: "pagi (AM)" },
  { word: "午後", reading: "ごご", meaning: "sore (PM)" },
  { word: "電気", reading: "でんき", meaning: "listrik" },
  { word: "電車", reading: "でんしゃ", meaning: "kereta listrik" },
  { word: "電話", reading: "でんわ", meaning: "telepon" },
  { word: "会話", reading: "かいわ", meaning: "percakapan" },
  { word: "食事", reading: "しょくじ", meaning: "makanan / makan" },
  { word: "食堂", reading: "しょくどう", meaning: "kantin" },
  { word: "自動車", reading: "じどうしゃ", meaning: "mobil" },
  { word: "自分", reading: "じぶん", meaning: "diri sendiri" },
  { word: "自転車", reading: "じてんしゃ", meaning: "sepeda" },
  { word: "家族", reading: "かぞく", meaning: "keluarga" },
  { word: "旅行", reading: "りょこう", meaning: "perjalanan" },
  { word: "写真", reading: "しゃしん", meaning: "foto" },
  { word: "英語", reading: "えいご", meaning: "bahasa Inggris" },
  { word: "日本語", reading: "にほんご", meaning: "bahasa Jepang" },
  { word: "音楽", reading: "おんがく", meaning: "musik" },
  { word: "病院", reading: "びょういん", meaning: "rumah sakit" },
  { word: "病気", reading: "びょうき", meaning: "penyakit" },
  { word: "映画", reading: "えいが", meaning: "film" },
  { word: "新聞", reading: "しんぶん", meaning: "koran" },
  { word: "地下鉄", reading: "ちかてつ", meaning: "kereta bawah tanah" },
  { word: "買い物", reading: "かいもの", meaning: "belanja" },
  { word: "料理", reading: "りょうり", meaning: "masakan" },
  { word: "理科", reading: "りか", meaning: "IPA" },
  { word: "数学", reading: "すうがく", meaning: "matematika" },
  { word: "文学", reading: "ぶんがく", meaning: "sastra" },
  { word: "安心", reading: "あんしん", meaning: "lega" },
  { word: "安全", reading: "あんぜん", meaning: "aman" },
  { word: "高校", reading: "こうこう", meaning: "SMA" },
  { word: "社長", reading: "しゃちょう", meaning: "direktur" },
  { word: "男子", reading: "だんし", meaning: "pria" },
  { word: "女子", reading: "じょし", meaning: "wanita" },
  { word: "男女", reading: "だんじょ", meaning: "pria dan wanita" },
  { word: "休日", reading: "きゅうじつ", meaning: "hari libur" },
  { word: "外出", reading: "がいしゅつ", meaning: "pergi keluar" },
  { word: "勉強", reading: "べんきょう", meaning: "belajar" },
  { word: "朝食", reading: "ちょうしょく", meaning: "sarapan" },
  { word: "夕食", reading: "ゆうしょく", meaning: "makan malam" },
  { word: "昼食", reading: "ちゅうしょく", meaning: "makan siang" },
  { word: "出発", reading: "しゅっぱつ", meaning: "keberangkatan" },
  { word: "到着", reading: "とうちゃく", meaning: "kedatangan" },
  { word: "準備", reading: "じゅんび", meaning: "persiapan" },
  { word: "連絡", reading: "れんらく", meaning: "kontak" },
  { word: "反対", reading: "はんたい", meaning: "berlawanan" },
  { word: "賛成", reading: "さんせい", meaning: "setuju" },
  { word: "意味", reading: "いみ", meaning: "arti" },
  { word: "注意", reading: "ちゅうい", meaning: "perhatian" },
  { word: "意見", reading: "いけん", meaning: "pendapat" },
  { word: "計画", reading: "けいかく", meaning: "rencana" },
  { word: "経験", reading: "けいけん", meaning: "pengalaman" },
  { word: "経済", reading: "けいざい", meaning: "ekonomi" },
  { word: "生活", reading: "せいかつ", meaning: "kehidupan" },
  { word: "活動", reading: "かつどう", meaning: "aktivitas" },
  { word: "運動", reading: "うんどう", meaning: "olahraga" },
  { word: "動物", reading: "どうぶつ", meaning: "hewan" },
  { word: "場所", reading: "ばしょ", meaning: "tempat" },
  { word: "場合", reading: "ばあい", meaning: "situasi" },
  { word: "建物", reading: "たてもの", meaning: "bangunan" },
  { word: "説明", reading: "せつめい", meaning: "penjelasan" },
  { word: "発明", reading: "はつめい", meaning: "penemuan" },
  { word: "空気", reading: "くうき", meaning: "udara" },
  { word: "空港", reading: "くうこう", meaning: "bandara" },
  { word: "海岸", reading: "かいがん", meaning: "pantai" },
  { word: "世界", reading: "せかい", meaning: "dunia" },
  { word: "季節", reading: "きせつ", meaning: "musim" },
  { word: "天気", reading: "てんき", meaning: "cuaca" },
  { word: "気分", reading: "きぶん", meaning: "perasaan" },
  { word: "平和", reading: "へいわ", meaning: "perdamaian" },
  { word: "理由", reading: "りゆう", meaning: "alasan" },
  { word: "自由", reading: "じゆう", meaning: "bebas" },
  { word: "関係", reading: "かんけい", meaning: "hubungan" },
  { word: "方法", reading: "ほうほう", meaning: "metode" },
  { word: "利用", reading: "りよう", meaning: "penggunaan" },
  { word: "目的", reading: "もくてき", meaning: "tujuan" },
  { word: "特別", reading: "とくべつ", meaning: "khusus" },
  { word: "全部", reading: "ぜんぶ", meaning: "semua" },
  { word: "部分", reading: "ぶぶん", meaning: "bagian" },
  { word: "心配", reading: "しんぱい", meaning: "khawatir" },
  { word: "交通", reading: "こうつう", meaning: "lalu lintas" },
  { word: "道具", reading: "どうぐ", meaning: "alat" },
  { word: "都合", reading: "つごう", meaning: "kenyamanan" },
  { word: "人気", reading: "にんき", meaning: "populer" },
  { word: "元気", reading: "げんき", meaning: "sehat" },
  { word: "最後", reading: "さいご", meaning: "terakhir" },
  { word: "最初", reading: "さいしょ", meaning: "pertama" },
  { word: "最高", reading: "さいこう", meaning: "terbaik" },
  { word: "最近", reading: "さいきん", meaning: "akhir-akhir ini" },
  { word: "最低", reading: "さいてい", meaning: "terendah" },
  { word: "辞書", reading: "じしょ", meaning: "kamus" },
  { word: "図書", reading: "としょ", meaning: "buku" },
  { word: "図書館", reading: "としょかん", meaning: "perpustakaan" },
  { word: "大使館", reading: "たいしかん", meaning: "kedutaan" },
  { word: "映画館", reading: "えいがかん", meaning: "bioskop" },
  { word: "美術館", reading: "びじゅつかん", meaning: "museum seni" },
  { word: "博物馆", reading: "はくぶつかん", meaning: "museum" },
  { word: "体育館", reading: "たいいくかん", meaning: "gymnasium" },
  { word: "旅館", reading: "りょかん", meaning: "penginapan Jepang" },
  { word: "練習", reading: "れんしゅう", meaning: "latihan" },
  { word: "自習", reading: "じしゅう", meaning: "belajar mandiri" },
  { word: "予習", reading: "よしゅう", meaning: "persiapan belajar" },
  { word: "復習", reading: "ふくしゅう", meaning: "mengulang pelajaran" },
  { word: "宿題", reading: "しゅくだい", meaning: "PR" },
  { word: "問題", reading: "もんだい", meaning: "masalah / soal" },
  { word: "話題", reading: "わだい", meaning: "topik pembicaraan" },
  { word: "質問", reading: "しつもん", meaning: "pertanyaan" },
  { word: "訪問", reading: "ほうもん", meaning: "kunjungan" },
  { word: "入院", reading: "にゅういん", meaning: "rawat inap" },
  { word: "退院", reading: "たいいん", meaning: "keluar RS" },
  { word: "院長", reading: "いんちょう", meaning: "kepala RS" },
  { word: "近所", reading: "きんじょ", meaning: "lingkungan sekitar" },
  { word: "住所", reading: "じゅうしょ", meaning: "alamat" },
  { word: "長所", reading: "ちょうしょ", meaning: "kelebihan" },
  { word: "短所", reading: "たんしょ", meaning: "kekurangan" },
  { word: "便所", reading: "べんじょ", meaning: "toilet" },
  { word: "役所", reading: "やくしょ", meaning: "kantor pemerintah" },
  { word: "台所", reading: "だいどころ", meaning: "dapur" },
  { word: "案内", reading: "あんない", meaning: "panduan" },
  { word: "家内", reading: "かない", meaning: "istri (sendiri)" },
  { word: "以内", reading: "いない", meaning: "dalam jangka" },
  { word: "以外", reading: "いがい", meaning: "selain" },
  { word: "都内", reading: "とない", meaning: "dalam kota" },
  { word: "車内", reading: "しゃない", meaning: "dalam mobil/kereta" },
  { word: "内部", reading: "ないぶ", meaning: "bagian dalam" },
  { word: "外部", reading: "がいぶ", meaning: "bagian luar" },
  { word: "海外", reading: "かいがい", meaning: "luar negeri" },
  { word: "外国", reading: "がいこく", meaning: "negara asing" },
  { word: "外国人", reading: "がいこくじん", meaning: "orang asing" },
  { word: "外食", reading: "がいしょく", meaning: "makan di luar" },
  { word: "中心", reading: "ちゅうしん", meaning: "pusat" },
  { word: "中学", reading: "ちゅうがく", meaning: "SMP" },
  { word: "校長", reading: "こうちょう", meaning: "kepala sekolah" },
  { word: "小学校", reading: "しょうがっこう", meaning: "SD" },
  { word: "中学校", reading: "ちゅうがっこう", meaning: "SMP (lengkap)" },
  { word: "入館", reading: "にゅうかん", meaning: "masuk gedung" },
  { word: "入口", reading: "いりぐち", meaning: "pintu masuk" },
  { word: "出口", reading: "でぐち", meaning: "pintu keluar" },
  { word: "入園", reading: "にゅうえん", meaning: "masuk taman" },
  { word: "公園", reading: "こうえん", meaning: "taman" },
  { word: "動物園", reading: "どうぶつえん", meaning: "kebun binatang" },
  { word: "遊園地", reading: "ゆうえんち", meaning: "taman bermain" },
  { word: "地面", reading: "じめん", meaning: "permukaan tanah" },
  { word: "地図", reading: "ちず", meaning: "peta" },
  { word: "地下", reading: "ちか", meaning: "bawah tanah" },
  { word: "地理", reading: "ちり", meaning: "geografi" },
  { word: "科学", reading: "かがく", meaning: "sains" },
  { word: "学者", reading: "がくしゃ", meaning: "sarjana" },
  { word: "作者", reading: "さくしゃ", meaning: "penulis" },
  { word: "医者", reading: "いしゃ", meaning: "dokter" },
  { word: "読者", reading: "どくしゃ", meaning: "pembaca" },
  { word: "若者", reading: "わかもの", meaning: "anak muda" },
  { word: "物理", reading: "ぶつり", meaning: "fisika" },
  { word: "心理", reading: "しんり", meaning: "psikologi" },
  { word: "理解", reading: "りかい", meaning: "paham" },
  { word: "解決", reading: "かいけつ", meaning: "solusi" },
  { word: "決心", reading: "けっしん", meaning: "tekad" },
  { word: "決定", reading: "けってい", meaning: "keputusan" },
  { word: "定休日", reading: "ていきゅうび", meaning: "hari libur tetap" },
  { word: "予定", reading: "よてい", meaning: "rencana / jadwal" },
  { word: "予約", reading: "よやく", meaning: "reservasi" },
  { word: "約束", reading: "やくそく", meaning: "janji" },
  { word: "婚約", reading: "こにゃく", meaning: "pertunangan" },
  { word: "要約", reading: "ようやく", meaning: "ringkasan" },
  { word: "表現", reading: "ひょうげん", meaning: "ekspresi" },
  { word: "現在", reading: "げんざい", meaning: "saat ini" },
  { word: "現金", reading: "げんきん", meaning: "uang tunai" },
  { word: "現代", reading: "げんだい", meaning: "era modern" },
  { word: "代理", reading: "だいり", meaning: "perwakilan" },
  { word: "代金", reading: "だいきん", meaning: "biaya" },
  { word: "時代", reading: "じだい", meaning: "era / zaman" },
  { word: "電力", reading: "でんりょく", meaning: "tenaga listrik" },
  { word: "電池", reading: "でんち", meaning: "baterai" },
  { word: "池", reading: "いけ", meaning: "kolam" },
  { word: "水槽", reading: "すいそう", meaning: "tangki air" },
  { word: "水道", reading: "すいどう", meaning: "saluran air" },
  { word: "書道", reading: "しょどう", meaning: "kaligrafi" },
  { word: "茶道", reading: "さどう", meaning: "upacara teh" },
  { word: "柔道", reading: "じゅうどう", meaning: "judo" },
  { word: "剣道", reading: "けんどう", meaning: "kendo" },
  { word: "北海道", reading: "ほっかいど", meaning: "Hokkaido" },
  { word: "道路", reading: "どうろ", meaning: "jalan raya" },
  { word: "線路", reading: "せんろ", meaning: "jalur kereta" },
  { word: "通路", reading: "つうろ", meaning: "lorong" },
  { word: "迷路", reading: "めいろ", meaning: "labirin" },
  { word: "活気", reading: "かっき", meaning: "semangat" },
  { word: "活用", reading: "かつよう", meaning: "aplikasi / penggunaan" },
  { word: "活躍", reading: "かつやく", meaning: "peran aktif" },
  { word: "自信", reading: "じしん", meaning: "percaya diri" },
  { word: "自動", reading: "じどう", meaning: "otomatis" },
  { word: "自然", reading: "しぜん", meaning: "alam" },
  { word: "突然", reading: "とつぜん", meaning: "tiba-tiba" },
  { word: "全然", reading: "ぜんぜん", meaning: "sama sekali tidak" },
  { word: "天然", reading: "てんねん", meaning: "alami" },
  { word: "工場", reading: "こうじょう", meaning: "pabrik" },
  { word: "工具", reading: "こうぐ", meaning: "peralatan" },
  { word: "工夫", reading: "くふ", meaning: "akal / ide" },
  { word: "工芸", reading: "こうげい", meaning: "kerajinan tangan" },
  { word: "人工", reading: "じんこう", meaning: "buatan manusia" },
  { word: "文章", reading: "ぶんしょう", meaning: "kalimat / teks" },
  { word: "文化", reading: "ぶんか", meaning: "budaya" },
  { word: "文法", reading: "ぶんぽう", meaning: "tata bahasa" },
  { word: "文字", reading: "もじ", meaning: "huruf" },
  { word: "見学", reading: "けんがく", meaning: "kunjungan studi" },
  { word: "発見", reading: "はっけん", meaning: "penemuan" },
  { word: "見物", reading: "けんぶつ", meaning: "tamasya" },
  { word: "見舞い", reading: "みまい", meaning: "menjenguk" },
  { word: "物語", reading: "ものがたり", meaning: "cerita" },
  { word: "敬語", reading: "けいご", meaning: "bahasa hormat" },
  { word: "単語", reading: "たんご", meaning: "kosakata" },
  { word: "国語", reading: "こくご", meaning: "bahasa nasional" },
  { word: "用語", reading: "ようご", meaning: "istilah" },
  { word: "言葉", reading: "ことば", meaning: "kata-kata" },
  { word: "千葉", reading: "ちば", meaning: "Chiba" },
  { word: "葉書", reading: "はがき", meaning: "kartu pos" },
  { word: "読書", reading: "どくしょ", meaning: "membaca buku" },
  { word: "書き取り", reading: "かきとり", meaning: "dikte" },
  { word: "書店", reading: "しょてん", meaning: "toko buku" },
  { word: "店員", reading: "てにん", meaning: "pegawai toko" },
  { word: "売店", reading: "ばいてん", meaning: "kios" },
  { word: "本店", reading: "ほんてん", meaning: "toko pusat" },
  { word: "喫茶店", reading: "きっさてん", meaning: "kafe" },
  { word: "百貨店", reading: "ひゃっかてん", meaning: "toserba" },
  { word: "飲食店", reading: "いんしょくてん", meaning: "restoran" },
  { word: "運賃", reading: "うんちん", meaning: "ongkos" },
  { word: "幸運", reading: "こううん", meaning: "keberuntungan" },
  { word: "不運", reading: "ふうん", meaning: "nasib buruk" },
  { word: "会場", reading: "かいじょう", meaning: "tempat acara" },
  { word: "場面", reading: "ばめん", meaning: "adegan" },
  { word: "面会", reading: "めんかい", meaning: "pertemuan" },
  { word: "面積", reading: "めんせき", meaning: "luas area" },
  { word: "真面目", reading: "まじめ", meaning: "serius" },
  { word: "正直", reading: "しょうじき", meaning: "jujur" },
  { word: "直接", reading: "ちょくせつ", meaning: "langsung" },
  { word: "直後", reading: "ちょくご", meaning: "segera setelah" },
  { word: "直前", reading: "ちょくぜん", meaning: "tepat sebelum" },
  { word: "特売", reading: "とくばい", meaning: "obral" },
  { word: "特有", reading: "とくゆう", meaning: "khas" },
  { word: "特色", reading: "とくしょく", meaning: "karakteristik" }
];
