export interface KotobaWord {
  word: string;
  reading: string;
  meaning: string;
}

export type KotobaCategory = 'compound' | 'adjective' | 'general';

const adjectiveKotoba = new Set([
  '有名',
  '安心',
  '安全',
  '特別',
  '人気',
  '元気',
  '楽しい',
  '難しい',
  '嬉しい',
  '忙しい',
  '簡単',
  '大丈夫',
  '大切',
  '便利',
  '好き',
  '嫌い',
  '上手',
  '下手',
  '静か',
  '賑やか',
  '真面目',
  '正直',
]);

export const getKotobaCategory = (word: string): KotobaCategory => {
  if (adjectiveKotoba.has(word)) return 'adjective';

  const hasKana = /[ぁ-んァ-ン]/.test(word);
  const kanjiCount = (word.match(/[一-龯々]/g) || []).length;

  if (!hasKana && kanjiCount >= 2) return 'compound';
  return 'general';
};

export const getKotobaCategoryLabel = (word: string): string => {
  const category = getKotobaCategory(word);
  if (category === 'compound') return 'Kata Majemuk';
  if (category === 'adjective') return 'Kata Sifat';
  return 'Umum';
};

export const kotobaList: KotobaWord[] = [
  { word: "毎日", reading: "まいにち", meaning: "setiap hari" },
  { word: "来年", reading: "らいねん", meaning: "tahun depan" },
  { word: "今年", reading: "ことし", meaning: "tahun ini" },
  { word: "今日", reading: "きょう", meaning: "hari ini" },
  { word: "明日", reading: "あした", meaning: "besok" },
  { word: "時計", reading: "とけい", meaning: "jam" },
  { word: "時間", reading: "じかん", meaning: "waktu" },
  { word: "会社", reading: "かいしゃ", meaning: "perusahaan" },
  { word: "学校", reading: "がっこう", meaning: "sekolah" },
  { word: "学生", reading: "がくせい", meaning: "siswa" },
  { word: "有名", reading: "ゆうめい", meaning: "terkenal" },
  { word: "名前", reading: "なまえ", meaning: "nama" },
  { word: "午前", reading: "ごぜん", meaning: "pagi (AM)" },
  { word: "午後", reading: "ごご", meaning: "sore (PM)" },
  { word: "電気", reading: "でんき", meaning: "listrik" },
  { word: "電車", reading: "でんしゃ", meaning: "kereta listrik" },
  { word: "電話", reading: "でんわ", meaning: "telepon" },
  { word: "会話", reading: "かいわ", meaning: "percakapan" },
  { word: "食事", reading: "しょくじ", meaning: "makanan / makan" },
  { word: "食堂", reading: "しょくどう", meaning: "kantin" },
  { word: "自動車", reading: "じどうしゃ", meaning: "mobil" },
  { word: "自分", reading: "じぶん", meaning: "diri sendiri" },
  { word: "自転車", reading: "じてんしゃ", meaning: "sepeda" },
  { word: "家族", reading: "かぞく", meaning: "keluarga" },
  { word: "友達", reading: "ともだち", meaning: "teman" },
  { word: "旅行", reading: "りょこう", meaning: "perjalanan" },
  { word: "写真", reading: "しゃしん", meaning: "foto" },
  { word: "英語", reading: "えいご", meaning: "bahasa Inggris" },
  { word: "日本語", reading: "にほんご", meaning: "bahasa Jepang" },
  { word: "音楽", reading: "おんがく", meaning: "musik" },
  { word: "病院", reading: "びょういん", meaning: "rumah sakit" },
  { word: "病気", reading: "びょうき", meaning: "penyakit" },
  { word: "風邪", reading: "かぜ", meaning: "flu / pilek" },
  { word: "薬", reading: "くすり", meaning: "obat" },
  { word: "映画", reading: "えいが", meaning: "film" },
  { word: "新聞", reading: "しんぶん", meaning: "koran" },
  { word: "地下鉄", reading: "ちかてつ", meaning: "kereta bawah tanah" },
  { word: "買い物", reading: "かいもの", meaning: "belanja" },
  { word: "料理", reading: "りょうり", meaning: "masakan" },
  { word: "安心", reading: "あんしん", meaning: "tenang / lega" },
  { word: "安全", reading: "あんぜん", meaning: "aman" },
  { word: "高校", reading: "こうこう", meaning: "SMA" },
  { word: "男子", reading: "だんし", meaning: "anak laki-laki" },
  { word: "女子", reading: "じょし", meaning: "anak perempuan" },
  { word: "男女", reading: "だんじょ", meaning: "pria dan wanita" },
  { word: "休日", reading: "きゅうじつ", meaning: "hari libur" },
  { word: "外出", reading: "がいしゅつ", meaning: "keluar rumah" },
  { word: "散歩", reading: "さんぽ", meaning: "jalan-jalan" },
  { word: "勉強", reading: "べんきょう", meaning: "belajar" },
  { word: "仕事", reading: "しごと", meaning: "pekerjaan / kerja" },
  { word: "朝食", reading: "ちょうしょく", meaning: "sarapan" },
  { word: "夕食", reading: "ゆうしょく", meaning: "makan malam" },
  { word: "昼食", reading: "ちゅうしょく", meaning: "makan siang" },
  { word: "食べ物", reading: "たべもの", meaning: "makanan" },
  { word: "飲み物", reading: "のみもの", meaning: "minuman" },
  { word: "出発", reading: "しゅっぱつ", meaning: "keberangkatan" },
  { word: "到着", reading: "とうちゃく", meaning: "kedatangan" },
  { word: "準備", reading: "じゅんび", meaning: "persiapan" },
  { word: "連絡", reading: "れんらく", meaning: "menghubungi / kontak" },
  { word: "反対", reading: "はんたい", meaning: "menentang / kebalikan" },
  { word: "賛成", reading: "さんせい", meaning: "setuju" },
  { word: "意味", reading: "いみ", meaning: "arti" },
  { word: "注意", reading: "ちゅうい", meaning: "hati-hati / perhatian" },
  { word: "計画", reading: "けいかく", meaning: "rencana" },
  { word: "経験", reading: "けいけん", meaning: "pengalaman" },
  { word: "生活", reading: "せいかつ", meaning: "kehidupan" },
  { word: "活動", reading: "かつどう", meaning: "aktivitas" },
  { word: "運動", reading: "うんどう", meaning: "olahraga" },
  { word: "動物", reading: "どうぶつ", meaning: "hewan" },
  { word: "場所", reading: "ばしょ", meaning: "tempat" },
  { word: "建物", reading: "たてもの", meaning: "bangunan" },
  { word: "部屋", reading: "へや", meaning: "kamar" },
  { word: "玄関", reading: "げんかん", meaning: "pintu masuk rumah" },
  { word: "空気", reading: "くうき", meaning: "udara" },
  { word: "空港", reading: "くうこう", meaning: "bandara" },
  { word: "海岸", reading: "かいがん", meaning: "pantai / pesisir" },
  { word: "季節", reading: "きせつ", meaning: "musim" },
  { word: "天気", reading: "てんき", meaning: "cuaca" },
  { word: "気分", reading: "きぶん", meaning: "perasaan" },
  { word: "特別", reading: "とくべつ", meaning: "istimewa / khusus" },
  { word: "全部", reading: "ぜんぶ", meaning: "semua" },
  { word: "交通", reading: "こうつう", meaning: "lalu lintas" },
  { word: "道具", reading: "どうぐ", meaning: "alat" },
  { word: "人気", reading: "にんき", meaning: "populer / terkenal" },
  { word: "元気", reading: "げんき", meaning: "sehat" },
  { word: "楽しい", reading: "たのしい", meaning: "menyenangkan" },
  { word: "難しい", reading: "むずかしい", meaning: "sulit" },
  { word: "嬉しい", reading: "うれしい", meaning: "senang" },
  { word: "忙しい", reading: "いそがしい", meaning: "sibuk" },
  { word: "簡単", reading: "かんたん", meaning: "mudah / sederhana" },
  { word: "大丈夫", reading: "だいじょうぶ", meaning: "tidak apa-apa / aman" },
  { word: "大切", reading: "たいせつ", meaning: "penting / berharga" },
  { word: "便利", reading: "べんり", meaning: "praktis / nyaman" },
  { word: "好き", reading: "すき", meaning: "suka" },
  { word: "嫌い", reading: "きらい", meaning: "tidak suka" },
  { word: "上手", reading: "じょうず", meaning: "pandai" },
  { word: "下手", reading: "へた", meaning: "kurang pandai" },
  { word: "静か", reading: "しずか", meaning: "tenang / sunyi" },
  { word: "賑やか", reading: "にぎやか", meaning: "ramai" },
  { word: "最後", reading: "さいご", meaning: "terakhir" },
  { word: "最初", reading: "さいしょ", meaning: "pertama" },
  { word: "最高", reading: "さいこう", meaning: "terbaik" },
  { word: "最近", reading: "さいきん", meaning: "akhir-akhir ini" },
  { word: "最低", reading: "さいてい", meaning: "terendah" },
  { word: "辞書", reading: "じしょ", meaning: "kamus" },
  { word: "図書館", reading: "としょかん", meaning: "perpustakaan" },
  { word: "映画館", reading: "えいがかん", meaning: "bioskop" },
  { word: "旅館", reading: "りょかん", meaning: "penginapan Jepang" },
  { word: "練習", reading: "れんしゅう", meaning: "latihan" },
  { word: "自習", reading: "じしゅう", meaning: "belajar mandiri" },
  { word: "予習", reading: "よしゅう", meaning: "belajar terlebih dahulu" },
  { word: "復習", reading: "ふくしゅう", meaning: "mengulang pelajaran" },
  { word: "宿題", reading: "しゅくだい", meaning: "PR" },
  { word: "問題", reading: "もんだい", meaning: "soal / masalah" },
  { word: "話題", reading: "わだい", meaning: "topik pembicaraan" },
  { word: "質問", reading: "しつもん", meaning: "pertanyaan" },
  { word: "訪問", reading: "ほうもん", meaning: "kunjungan" },
  { word: "近所", reading: "きんじょ", meaning: "lingkungan sekitar" },
  { word: "住所", reading: "じゅうしょ", meaning: "alamat" },
  { word: "便所", reading: "べんじょ", meaning: "toilet / jamban" },
  { word: "駅", reading: "えき", meaning: "stasiun" },
  { word: "銀行", reading: "ぎんこう", meaning: "bank" },
  { word: "郵便局", reading: "ゆうびんきょく", meaning: "kantor pos" },
  { word: "役所", reading: "やくしょ", meaning: "kantor pemerintah" },
  { word: "台所", reading: "だいどころ", meaning: "dapur" },
  { word: "案内", reading: "あんない", meaning: "panduan" },
  { word: "車内", reading: "しゃない", meaning: "di dalam kendaraan" },
  { word: "海外", reading: "かいがい", meaning: "luar negeri" },
  { word: "外国", reading: "がいこく", meaning: "negara asing" },
  { word: "外国人", reading: "がいこくじん", meaning: "orang asing" },
  { word: "外食", reading: "がいしょく", meaning: "makan di luar" },
  { word: "中心", reading: "ちゅうしん", meaning: "pusat" },
  { word: "中学", reading: "ちゅうがく", meaning: "SMP" },
  { word: "校長", reading: "こうちょう", meaning: "kepala sekolah" },
  { word: "小学校", reading: "しょうがっこう", meaning: "SD" },
  { word: "中学校", reading: "ちゅうがっこう", meaning: "SMP (lengkap)" },
  { word: "入口", reading: "いりぐち", meaning: "pintu masuk" },
  { word: "出口", reading: "でぐち", meaning: "pintu keluar" },
  { word: "受付", reading: "うけつけ", meaning: "loket / resepsionis" },
  { word: "切符", reading: "きっぷ", meaning: "tiket" },
  { word: "改札", reading: "かいさつ", meaning: "gerbang tiket" },
  { word: "乗り場", reading: "のりば", meaning: "tempat naik" },
  { word: "降り場", reading: "おりば", meaning: "tempat turun" },
  { word: "公園", reading: "こうえん", meaning: "taman" },
  { word: "動物園", reading: "どうぶつえん", meaning: "kebun binatang" },
  { word: "遊園地", reading: "ゆうえんち", meaning: "taman bermain" },
  { word: "地面", reading: "じめん", meaning: "permukaan tanah" },
  { word: "地図", reading: "ちず", meaning: "peta" },
  { word: "地下", reading: "ちか", meaning: "bawah tanah" },
  { word: "医者", reading: "いしゃ", meaning: "dokter" },
  { word: "若者", reading: "わかもの", meaning: "anak muda" },
  { word: "理解", reading: "りかい", meaning: "paham" },
  { word: "解決", reading: "かいけつ", meaning: "solusi" },
  { word: "決心", reading: "けっしん", meaning: "tekad" },
  { word: "決定", reading: "けってい", meaning: "keputusan" },
  { word: "定休日", reading: "ていきゅうび", meaning: "hari libur tetap" },
  { word: "予定", reading: "よてい", meaning: "rencana / jadwal" },
  { word: "予約", reading: "よやく", meaning: "reservasi" },
  { word: "約束", reading: "やくそく", meaning: "janji" },
  { word: "用事", reading: "ようじ", meaning: "urusan / keperluan" },
  { word: "趣味", reading: "しゅみ", meaning: "hobi" },
  { word: "現金", reading: "げんきん", meaning: "uang tunai" },
  { word: "代金", reading: "だいきん", meaning: "harga / biaya" },
  { word: "電池", reading: "でんち", meaning: "baterai" },
  { word: "池", reading: "いけ", meaning: "kolam" },
  { word: "水道", reading: "すいどう", meaning: "saluran air" },
  { word: "道路", reading: "どうろ", meaning: "jalan raya" },
  { word: "線路", reading: "せんろ", meaning: "jalur kereta" },
  { word: "通路", reading: "つうろ", meaning: "lorong" },
  { word: "自信", reading: "じしん", meaning: "percaya diri" },
  { word: "自動", reading: "じどう", meaning: "otomatis" },
  { word: "自然", reading: "しぜん", meaning: "alam" },
  { word: "突然", reading: "とつぜん", meaning: "tiba-tiba" },
  { word: "全然", reading: "ぜんぜん", meaning: "sama sekali tidak" },
  { word: "天然", reading: "てんねん", meaning: "alami" },
  { word: "洗濯", reading: "せんたく", meaning: "mencuci pakaian" },
  { word: "掃除", reading: "そうじ", meaning: "bersih-bersih" },
  { word: "工具", reading: "こうぐ", meaning: "perkakas / alat kerja" },
  { word: "工夫", reading: "くふう", meaning: "akal / upaya" },
  { word: "文字", reading: "もじ", meaning: "huruf" },
  { word: "発見", reading: "はっけん", meaning: "penemuan" },
  { word: "見舞い", reading: "みまい", meaning: "menjenguk orang sakit" },
  { word: "言葉", reading: "ことば", meaning: "kata / ungkapan" },
  { word: "千葉", reading: "ちば", meaning: "Chiba" },
  { word: "葉書", reading: "はがき", meaning: "kartu pos" },
  { word: "読書", reading: "どくしょ", meaning: "membaca buku" },
  { word: "書店", reading: "しょてん", meaning: "toko buku" },
  { word: "店員", reading: "てんいん", meaning: "pegawai toko" },
  { word: "売店", reading: "ばいてん", meaning: "kios" },
  { word: "喫茶店", reading: "きっさてん", meaning: "kafe" },
  { word: "百貨店", reading: "ひゃっかてん", meaning: "toserba" },
  { word: "飲食店", reading: "いんしょくてん", meaning: "restoran" },
  { word: "運賃", reading: "うんちん", meaning: "ongkos" },
  { word: "幸運", reading: "こううん", meaning: "keberuntungan" },
  { word: "不運", reading: "ふうん", meaning: "nasib buruk" },
  { word: "熱", reading: "ねつ", meaning: "demam / panas" },
  { word: "会場", reading: "かいじょう", meaning: "tempat acara" },
  { word: "真面目", reading: "まじめ", meaning: "serius / sungguh-sungguh" },
  { word: "正直", reading: "しょうじき", meaning: "jujur" },
  { word: "特売", reading: "とくばい", meaning: "obral" },
];
